import type {
  Booking,
  DocumentAttachment,
  Driver,
  MaintenanceSchedule,
  NotificationItem,
  Renter,
  Trip,
  Vehicle,
} from './types'

export const vehiclesSeed: Vehicle[] = [
  {
    id: 'vehicle-1',
    plateNumber: 'MBZ-1024',
    mvFileNumber: '1301-000241',
    engineNumber: '2GD-884201',
    chassisVinNumber: 'MROAB8FSX00241024',
    make: 'Toyota',
    model: 'Innova',
    seriesVariant: '2.8 E Diesel',
    yearModel: 2022,
    color: 'White',
    vehicleType: 'MPV',
    bodyType: 'Wagon',
    fuelType: 'Diesel',
    passengerCapacity: 7,
    classification: 'Private',
    grossWeight: '2,150 kg',
    currentOdometer: 35240,
    ownershipStatus: 'Owned',
    status: 'Available',
    remarks: 'Primary airport rental unit',
  },
  {
    id: 'vehicle-2',
    plateNumber: 'MBZ-2048',
    mvFileNumber: '1301-000512',
    engineNumber: '4N14-662018',
    chassisVinNumber: 'MMBJNKB40MD204800',
    make: 'Mitsubishi',
    model: 'L300',
    seriesVariant: 'Exceed',
    yearModel: 2021,
    color: 'Silver',
    vehicleType: 'Van',
    bodyType: 'Delivery Van',
    fuelType: 'Diesel',
    passengerCapacity: 3,
    classification: 'Logistics',
    grossWeight: '2,350 kg',
    currentOdometer: 61200,
    ownershipStatus: 'Financed',
    status: 'Booked',
    remarks: 'Corporate delivery route',
  },
]

export const driversSeed: Driver[] = [
  {
    id: 'driver-1',
    fullName: 'Miguel Santos',
    address: 'Pasay City, Metro Manila',
    contactNumber: '+63 917 555 0142',
    email: 'miguel.driver@example.com',
    emergencyContact: 'Ana Santos - +63 917 555 0111',
    licenseNumber: 'N01-23-456789',
    licenseTypeRestrictions: 'Professional, Restriction B/B1',
    licenseExpirationDate: '2027-01-30',
    status: 'Active',
    notes: 'Preferred for airport and executive bookings',
  },
  {
    id: 'driver-2',
    fullName: 'Carlo Reyes',
    address: 'Quezon City, Metro Manila',
    contactNumber: '+63 918 555 0199',
    email: 'carlo.driver@example.com',
    emergencyContact: 'Lina Reyes - +63 918 555 0100',
    licenseNumber: 'N02-88-224466',
    licenseTypeRestrictions: 'Professional, Restriction B/B2',
    licenseExpirationDate: '2026-06-08',
    status: 'Active',
    notes: 'Delivery/logistics specialist',
  },
]

export const rentersSeed: Renter[] = [
  {
    id: 'renter-1',
    fullName: 'Alyssa Cruz',
    address: 'BGC, Taguig',
    contactNumber: '+63 919 555 0101',
    email: 'alyssa@example.com',
    validIdType: 'Passport',
    validIdNumber: 'P1234567A',
    emergencyContact: 'Ramon Cruz - +63 919 555 0102',
    isWatchlisted: false,
    notes: 'Frequent airport pickup customer',
  },
  {
    id: 'renter-2',
    fullName: 'Northstar Trading Corp.',
    address: 'Makati City',
    contactNumber: '+63 2 8555 0188',
    email: 'operations@northstar.example',
    validIdType: 'SEC Registration',
    validIdNumber: 'CS202312345',
    emergencyContact: 'Operations Desk',
    isWatchlisted: false,
    notes: 'Corporate logistics account',
  },
  {
    id: 'renter-3',
    fullName: 'Jose Villanueva',
    address: 'Paranaque City',
    contactNumber: '+63 920 555 0133',
    email: 'jose@example.com',
    validIdType: 'Driver License',
    validIdNumber: 'D11-44-998877',
    driverLicenseNumber: 'D11-44-998877',
    emergencyContact: 'Mara Villanueva',
    isWatchlisted: false,
    notes: 'Self-drive approved',
  },
]

export const bookingsSeed: Booking[] = [
  {
    id: 'booking-1',
    referenceNumber: 'BK-2026-0001',
    renterId: 'renter-1',
    vehicleId: 'vehicle-1',
    driverId: 'driver-1',
    bookingType: 'With driver',
    startDateTime: '2026-05-16T08:00',
    endDateTime: '2026-05-18T18:00',
    pickupLocation: 'NAIA Terminal 3',
    returnLocation: 'BGC Taguig',
    rateType: 'Daily',
    rateAmount: 4200,
    securityDeposit: 5000,
    paymentStatus: 'Partial',
    bookingStatus: 'Confirmed',
    notes: 'Airport pickup, child seat requested',
  },
  {
    id: 'booking-2',
    referenceNumber: 'BK-2026-0002',
    renterId: 'renter-2',
    vehicleId: 'vehicle-2',
    driverId: 'driver-2',
    bookingType: 'Delivery/logistics',
    startDateTime: '2026-05-14T07:00',
    endDateTime: '2026-05-17T19:00',
    pickupLocation: 'Makati Warehouse',
    returnLocation: 'Quezon City Hub',
    rateType: 'Custom',
    rateAmount: 18500,
    securityDeposit: 0,
    paymentStatus: 'Paid',
    bookingStatus: 'Active',
    notes: 'Three-day fulfillment route',
  },
  {
    id: 'booking-3',
    referenceNumber: 'BK-2026-0003',
    renterId: 'renter-3',
    vehicleId: 'vehicle-1',
    bookingType: 'Self-drive',
    startDateTime: '2026-05-24T09:00',
    endDateTime: '2026-05-26T17:00',
    pickupLocation: 'BeezFleet Garage',
    returnLocation: 'BeezFleet Garage',
    rateType: 'Daily',
    rateAmount: 3600,
    securityDeposit: 8000,
    paymentStatus: 'Unpaid',
    bookingStatus: 'Pending',
    notes: 'Awaiting signed agreement',
  },
]

export const tripsSeed: Trip[] = [
  {
    id: 'trip-1',
    tripNumber: 'TR-2026-0001',
    bookingReference: 'BK-2026-0002',
    vehicleId: 'vehicle-2',
    driverId: 'driver-2',
    renterId: 'renter-2',
    tripType: 'Delivery',
    startDateTime: '2026-05-14T07:00',
    startingOdometer: 60980,
    endingOdometer: 61200,
    fuelExpense: 3200,
    tollExpense: 820,
    parkingExpense: 180,
    otherExpenses: 0,
    grossRevenue: 18500,
    driverProceedCommission: 2500,
    paymentMethod: 'Bank transfer',
    paymentStatus: 'Paid',
    remarks: 'Active route with daily POD uploads',
    status: 'Active',
  },
  {
    id: 'trip-2',
    tripNumber: 'TR-2026-0002',
    vehicleId: 'vehicle-1',
    driverId: 'driver-1',
    renterId: 'renter-1',
    tripType: 'Private booking',
    startDateTime: '2026-05-02T08:00',
    endDateTime: '2026-05-03T20:00',
    startingOdometer: 34820,
    endingOdometer: 35020,
    fuelExpense: 2100,
    tollExpense: 640,
    parkingExpense: 120,
    otherExpenses: 0,
    grossRevenue: 9500,
    driverProceedCommission: 1500,
    paymentMethod: 'GCash',
    paymentStatus: 'Paid',
    remarks: 'Completed without incident',
    status: 'Completed',
  },
  {
    id: 'trip-3',
    tripNumber: 'TR-2026-0003',
    bookingReference: 'BK-2026-0001',
    vehicleId: 'vehicle-1',
    driverId: 'driver-1',
    renterId: 'renter-1',
    tripType: 'Rental',
    startDateTime: '2026-05-16T08:00',
    fuelExpense: 0,
    tollExpense: 0,
    parkingExpense: 0,
    otherExpenses: 0,
    grossRevenue: 12600,
    driverProceedCommission: 0,
    paymentMethod: 'Cash',
    paymentStatus: 'Partial',
    remarks: 'Scheduled from confirmed booking',
    status: 'Scheduled',
  },
]

export const maintenanceSeed: MaintenanceSchedule[] = [
  {
    id: 'pms-1',
    vehicleId: 'vehicle-1',
    title: '10,000 km PMS',
    dueDate: '2026-06-02',
    dueOdometer: 36000,
    status: 'Due Soon',
    vendorShop: 'BeezFleet Partner Garage',
    estimatedCost: 8500,
    notes: 'Oil, filters, brake inspection',
  },
  {
    id: 'pms-2',
    vehicleId: 'vehicle-2',
    title: 'Brake and suspension inspection',
    dueDate: '2026-05-20',
    dueOdometer: 62000,
    status: 'Due Soon',
    vendorShop: 'North EDSA Auto Care',
    estimatedCost: 12000,
    notes: 'High priority after logistics route',
  },
]

export const documentsSeed: DocumentAttachment[] = [
  {
    id: 'doc-1',
    entityType: 'Vehicle',
    entityId: 'vehicle-1',
    originalFileName: 'MBZ-1024-insurance.pdf',
    fileUrl: '#',
    documentType: 'Insurance Policy',
    expirationDate: '2026-06-05',
    uploadedAt: '2026-05-01T10:00',
  },
  {
    id: 'doc-2',
    entityType: 'Driver',
    entityId: 'driver-2',
    originalFileName: 'carlo-license-front.jpg',
    fileUrl: '#',
    documentType: 'Driver License',
    expirationDate: '2026-06-08',
    uploadedAt: '2026-04-28T13:30',
  },
  {
    id: 'doc-3',
    entityType: 'Booking',
    entityId: 'booking-1',
    originalFileName: 'signed-rental-agreement.pdf',
    fileUrl: '#',
    documentType: 'Signed Contract',
    uploadedAt: '2026-05-12T09:00',
  },
]

export const notificationsSeed: NotificationItem[] = [
  {
    id: 'notification-1',
    title: 'PMS reminder',
    message: 'MBZ-2048 brake and suspension inspection is due within 7 days.',
    type: 'PMS Reminder',
    isRead: false,
    createdAt: '2026-05-15T08:10',
  },
  {
    id: 'notification-2',
    title: 'Driver license expiring soon',
    message: 'Carlo Reyes license expires on 2026-06-08.',
    type: 'Driver License Expiry',
    isRead: false,
    createdAt: '2026-05-15T08:00',
  },
  {
    id: 'notification-3',
    title: 'Booking confirmed',
    message: 'BK-2026-0001 is ready to convert into a trip.',
    type: 'Booking',
    isRead: true,
    createdAt: '2026-05-14T16:45',
  },
]
